DELETE FROM Computers;
DELETE FROM CustomerOrders;
DELETE FROM CustomerPaymentTypes;
DELETE FROM Customers;
DELETE FROM Departments;
DELETE FROM EmployeeComputers;
DELETE FROM EmployeeTrainings;
DELETE FROM Employees;
DELETE FROM Orders;
DELETE FROM PaymentTypes;
DELETE FROM ProductTypes;
DELETE FROM Products;
DELETE FROM Trainings;

DROP TABLE IF EXISTS Computers;
DROP TABLE IF EXISTS CustomerOrders;
DROP TABLE IF EXISTS CustomerPaymentTypes;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS EmployeeComputers;
DROP TABLE IF EXISTS EmployeeTrainings;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS PaymentTypes;
DROP TABLE IF EXISTS ProductTypes;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Trainings;